### ISSUE TITLE
.setNickname imposible

### ISSUE THREAD

**Issue by steodec** [Alfr3XD/discordcards#1]
Hello

I didn't understand why the code tell me it's not a string
because when i make console.log of member.displayname, i have string for answer

Error: `El apodo /*nickname/* no está ingresado en tipo string, en su lugar se ingresó: string`

Code:
```ts
const canvas = await new LevelCard()
            .setLevel(level.Level)
            .setXp(level.XP, reqXP)
            .setRank(rank)
            .setUsername(member.user.username)
            .setNickname(member.displayName) //
            .setAvatar(member.user.avatarURL({size: 512, extension: 'jpeg'}))
            .render()
```

**Comment by Alfr3XD** [comment]
Oops, I hadn't realized that the property in the condition was entered correctly, but I've fixed that now.
It should work for you now.

**Comment by steodec** [comment]
I try this today
